name: "âš¡Tests"

on:
  pull_request:
  push:
    branches: ["main", "release/*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
      - name: "Install bun"
        # For running things and for package management "
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.22 # Values: latest, <sha>, 1.2.3, canary
        # Outputs:
        # - cache-hit    : Whether the executable was read from cache. Ex. "true"
        # - bun-version  : The output from running `bun-version`. Ex. "1.0.0"
        # - bun-revision : The output from running `bun-revision`.
      - run: |
          bun install
      - run: |
          bun test
