name: "âš¡Tests"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: ["main", "release/*"]

# Allow concurrent runs on main/release branches but isolates other branches
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
      - name: "Install bun" # For running things and TS package management"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.22 # Values: latest, <sha>, 1.2.3, canary
        # Outputs:
        # - cache-hit    : Whether the executable was read from cache. Ex. "true"
        # - bun-version  : The output from running `bun-version`. Ex. "1.0.0"
        # - bun-revision : The output from running `bun-revision`.
      - run: |
          bun install
      - run: |
          bun test
